apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-web-app
  namespace: prj-antonio-minelli
  labels:
    app: web-app
data:
  DB_HOST: svc-mysql-db  
  DB_USER: root
  DB_PASSWORD: Password123
  