apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-custom
  namespace: prj-antonio-minelli
provisioner: file.csi.azure.com
parameters:
  resourceGroup: CORSO-DGS00035-OpenShift-storage
  storageAccount: storagearodemo
  shareName: appshare
  secretName: secret-azure-demo
  secretNamespace: prj-antonio-minelli
  protocol: SMB
  skuName: Standard_LRS
# Reclaim policy: Delete (default) o Retain
# su delete kubernetes elimina anche il volume creato in Azure, su retain lo lascia
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  -dir_mode=0777
  -file_mode=0777
  -uid=1000
  -gid=1000