apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-demo
  namespace: prj-antonio-minelli
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-custom
  resources:
    requests:
      storage: 5Gi
  