apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-demo
  namespace: prj-antonio-minelli
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
  