apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-cutom
  namespace: prj-antonio-minelli
  labels:
    app: web-app
data:
  app.properties: |
    server.port=8080
    server.context-path=/app
    server.timeout=30s

    spring.application.name=demo
    spring.profile.active=dev

    metrics.enabled=true
  
  database.properties: |
    db.host=svc-mysql-db
    db.user=root
    db.password=Password123

  logging.yaml: |
    logging:
      level:
        root: INFO
        com.example: DEBUG
